namespace AccountingInventory.Application.Sales.Products;

public sealed record SalesProductSummary(
    Guid Id,
    string ProductId,
    string ProductName,
    string SerialNumber,
    Guid CustomerId,
    string CustomerName,
    string CustomerMobile,
    string CustomerAddress,
    string? CustomerEmail,
    DateOnly SaleDate,
    int PaymentTermsDays,
    DateOnly DueDate,
    decimal ProductPrice,
    decimal SellingPrice,
    decimal Discount,
    Guid? TaxId,
    decimal CgstRate,
    decimal SgstRate,
    decimal TaxableAmount,
    decimal CgstAmount,
    decimal SgstAmount,
    decimal TotalAmount,
    bool IsActive,
    string? PaymentMode,
    string BillNumber);
