// <auto-generated />
using AccountingInventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountingInventory.Infrastructure.Migrations;

[DbContext(typeof(AccountingInventoryDbContext))]
[Migration("20260917000000_InitialTenantSchema")]
partial class InitialTenantSchema
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The runtime model is schema-independent; table resolution comes from the
        // connection search_path configured by TenantSchemaMigrator.
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");
    }
}
